username: you@example.com
password: your-password
courses:
    - https://code.tutsplus.com/courses/getting-started-with-python
    - https://code.tutsplus.com/courses/foundational-flask-creating-your-own-static-blog-generator
